---
- hosts: linux_hosts
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: Create a file in /opt for RedHat 6
      file: path=/opt/rhel6 state=touch
      when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version  == '6'

    - name: Create a file in /opt for RedHat 7
      file: path=/opt/rhel7 state=touch
      when: (ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS') and ansible_distribution_major_version == '7'


    - name: Create a file in /opt for Debian 8
      file: path=/opt/debian8 state=touch
      when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'

    - name: Create a file in /opt for Ubuntu 14
      file: path=/opt/ubuntu14 state=touch
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version == '14'
