---
- name: Deploy OCS Agent for Debian 8
  unarchive:  src={{ ocs_agent_package_debian_8 }} dest=/
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '8'

- name: Deploy OCS Agent for Debian 7
  unarchive:  src={{ ocs_agent_package_debian_7 }} dest=/
  when: ansible_distribution == 'Debian' and ansible_distribution_major_version == '7'
